{
 "title": "Prometheus JMX  for Kubernetes Pod",
 "description": "After selecting your namespace and pod you get a wealth of JVM based metrics",
 "tags": [
  "JMX",
  "Kubernetes",
  "pod"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(jvm_memory_bytes_used, namespace)"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values(jvm_memory_bytes_used{namespace=\"$namespace\"}, pod)"
   },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(jvm_memory_bytes_used{pod=\"$pod\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Start time",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_start_time_seconds{instance=\"$instance\"}*1000"
    }
   ]
  },
  {
   "title": "JVM Version",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 7, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "label_join(jvm_info{instance=\"$instance\"}, \"jdk\", \", \", \"vendor\", \"runtime\", \"version\")"
    }
   ]
  },
  {
   "title": "Metaspace (average per pod)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{pod=\"$pod\", namespace=\"$namespace\", pool=\"Metaspace\"}",
     "legendFormat": "Max {{kubernetes_pod_name}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pod=\"$pod\", namespace=\"$namespace\", pool=\"Metaspace\"}",
     "legendFormat": "Used {{kubernetes_pod_name}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pod=\"$pod\", namespace=\"$namespace\", pool=\"Metaspace\"}",
     "legendFormat": "Committed {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "GC count increase (avg per pod)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_count{pod=\"$pod\", namespace=\"$namespace\"}[$__interval])",
     "legendFormat": "{{gc}}  {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "GC time (average per pod)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{pod=\"$pod\", namespace=\"$namespace\"}[5m])",
     "legendFormat": "{{gc}} {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Memory area-heap",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "repeat": "memarea",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\",instance=\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": " jvm_memory_bytes_max{area=\"heap\",instance=\"$instance\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\",instance=\"$instance\"} / jvm_memory_bytes_max >= 0",
     "legendFormat": "Usage %"
    }
   ]
  },
  {
   "title": "Heap used (relative to request)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum((jvm_memory_bytes_used{pod=\"$pod\", namespace=\"$namespace\", area=\"heap\"})) / sum((jvm_memory_bytes_max{area=\"heap\",pod=\"$pod\"}))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Heap (per pod)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_max{pod=\"$pod\", namespace=\"$namespace\", area=\"heap\"}) / count(jvm_memory_bytes_max{pod=\"$pod\", namespace=\"$namespace\", area=\"heap\"})",
     "legendFormat": "Max limit"
    },
    {
     "expr": "jvm_memory_bytes_used{pod=\"$pod\", namespace=\"$namespace\", area=\"heap\"}",
     "legendFormat": "Used {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Non Heap (per pod)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{pod=\"$pod\", namespace=\"$namespace\", area=\"nonheap\"}",
     "legendFormat": "Used  {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "GC count (avg per pod)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_count{pod=\"$pod\", namespace=\"$namespace\"}",
     "legendFormat": "{{gc}}  {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "GC time increase (avg per pod)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{pod=\"$pod\", namespace=\"$namespace\"}[$__interval])",
     "legendFormat": "{{gc}}  {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Code Cache (average per pod)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{pod=\"$pod\", namespace=\"$namespace\", pool=\"Code Cache\"}",
     "legendFormat": "Max {{kubernetes_pod_name}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pod=\"$pod\", namespace=\"$namespace\", pool=\"Code Cache\"}",
     "legendFormat": "Used {{kubernetes_pod_name}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pod=\"$pod\", namespace=\"$namespace\", pool=\"Code Cache\"}",
     "legendFormat": "Committed {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Compressed Class Space (average per pod)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{pool=\"Compressed Class Space\", pod=\"$pod\", namespace=\"$namespace\"}",
     "legendFormat": "Max {{kubernetes_pod_name}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"Compressed Class Space\", pod=\"$pod\", namespace=\"$namespace\"}",
     "legendFormat": "Used {{kubernetes_pod_name}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=\"Compressed Class Space\", pod=\"$pod\", namespace=\"$namespace\"}",
     "legendFormat": "Committed {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Threads used (avg per pod)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{pod=\"$pod\", namespace=\"$namespace\"}",
     "legendFormat": "JVM current threads   {{kubernetes_pod_name}}"
    },
    {
     "expr": "jvm_threads_daemon{pod=\"$pod\", namespace=\"$namespace\"}",
     "legendFormat": "JVM daemon threads  {{kubernetes_pod_name}}"
    },
    {
     "expr": "jvm_threads_deadlocked{pod=\"$pod\", namespace=\"$namespace\"}",
     "legendFormat": "JVM deadlocked threads  {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Class Loading (average per pod)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded{pod=\"$pod\", namespace=\"$namespace\"}",
     "legendFormat": "loaded  {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Par Eden Space (average per pod)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{pod=\"$pod\", namespace=\"$namespace\", pool=\"Par Eden Space\"}",
     "legendFormat": "Max {{kubernetes_pod_name}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pod=\"$pod\", namespace=\"$namespace\", pool=\"Par Eden Space\"}",
     "legendFormat": "Used {{kubernetes_pod_name}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pod=\"$pod\", namespace=\"$namespace\", pool=\"Par Eden Space\"}",
     "legendFormat": "Committed {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "CMS Old Gen (average per pod)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 52 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{pod=\"$pod\", namespace=\"$namespace\", pool=\"CMS Old Gen\"}",
     "legendFormat": "Max {{kubernetes_pod_name}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pod=\"$pod\", namespace=\"$namespace\", pool=\"CMS Old Gen\"}",
     "legendFormat": "Used {{kubernetes_pod_name}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pod=\"$pod\", namespace=\"$namespace\", pool=\"CMS Old Gen\"}",
     "legendFormat": "Committed {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Par Survivor Space (average per pod)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 52 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{pod=\"$pod\", namespace=\"$namespace\", pool=\"Par Survivor Space\"}",
     "legendFormat": "Max {{kubernetes_pod_name}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pod=\"$pod\", namespace=\"$namespace\", pool=\"Par Survivor Space\"}",
     "legendFormat": "Used {{kubernetes_pod_name}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pod=\"$pod\", namespace=\"$pod\", pool=\"Par Survivor Space\"}",
     "legendFormat": "Committed {{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}