---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-spec: slb.s1.small
    service.beta.kubernetes.io/alicloud-loadbalancer-address-type: intranet
  name: demo-app
  labels:
    app: demo-app
spec:
  ports:
    - name: http-app
      port: 8080
      protocol: TCP
      targetPort: http-app
    - name: http-jvm
      port: 20000
      protocol: TCP
      targetPort: http-jvm
  selector:
    app: demo-app
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  labels:
    app: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      imagePullSecrets:
      - name: reg-secret
      # nodeSelector:
      #   kubernetes.io/hostname: 10.177.92.6
      containers:
      - name: demo-app
        image: currycan/demo-jmx:0.0.1
        imagePullPolicy: IfNotPresent
        ports:
        - name: http-app
          containerPort: 8080
        - name: http-jvm
          containerPort: 20000
        lifecycle:
          postStart:
            exec:
              command:
              - /bin/sh
              - -c
              - sleep 0.5
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - sleep 8
        env:
        - name: JAVA_OPTS
          value: "-Xms1024m -Xmx1024m -Xmn384m -Xss1m -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=128m -XX:MaxDirectMemorySize=256m -XX:NewRatio=2 -XX:SurvivorRatio=8 -XX:+AggressiveOpts -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSParallelRemarkEnabled -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=70 -XX:LargePageSizeInBytes=128m -XX:-UseBiasedLocking -XX:AutoBoxCacheMax=20000 -XX:+AlwaysPreTouch -Djava.awt.headless=true -Djava.security.egd=file:/dev/./urandom"
        - name: TZ
          value: Asia/Shanghai
        # - name: aliyun_logs_debug
        #   value: "stdout"
        - name: aliyun_logs_demo-app
          value: "/logs/app-demo/info.log"
        - name: aliyun_logs_demo-app_tags
          value: app=demo-app
        # - name: aliyun_logs_debug_target
        #   value: "tpc_lklp_glb_log_k8s-demo-app"
        - name: aliyun_logs_demo-app_target
          value: "tpc_lklp_glb_log_k8s-demo-app"
        resources:
          limits:
            cpu: '2'
            memory: 2048Mi
          requests:
            cpu: '125m'
            memory: 1024Mi
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 2
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 8
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 2
